version: "3.9"
services:
  tomcat:
    container_name: aplicacionjava
    image: tomcat:9.0
    volumes:
    - ./sample.war:/usr/local/tomcat/webapps/sample.war
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
